// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
public partial class Concessao
{
    [Column("CCCDFUN")]
    public int Cccdfun { get; set; }

    [Column("CCCDUSU")]
    public int Cccdusu { get; set; }

    [ForeignKey("Cccdfun")]
    public virtual Funcionalidades CccdfunNavigation { get; set; }

    [ForeignKey("Cccdusu")]
    public virtual Usuario CccdusuNavigation { get; set; }
}