// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class CUSTOMSYSContext : DbContext
{
    public CUSTOMSYSContext(DbContextOptions<CUSTOMSYSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Concessao> Concessao { get; set; }

    public virtual DbSet<Enderecos> Enderecos { get; set; }

    public virtual DbSet<Funcionalidades> Funcionalidades { get; set; }

    public virtual DbSet<Nacionalidades> Nacionalidades { get; set; }

    public virtual DbSet<SituacaoCliente> SituacaoCliente { get; set; }

    public virtual DbSet<TipoCliente> TipoCliente { get; set; }

    public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.Clid).HasName("PK__Clientes__F6BA78E785E84302");

            entity.Property(e => e.Clsexo).IsFixedLength();

            entity.HasOne(d => d.ClcdenderecoNavigation).WithMany(p => p.Clientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Enderecos_Cliente");

            entity.HasOne(d => d.ClcdsituacaoNavigation).WithMany(p => p.Clientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SituacaoCliente_Cliente");

            entity.HasOne(d => d.ClcdtipoclienteNavigation).WithMany(p => p.Clientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TipoCliente_Cliente");

            entity.HasOne(d => d.ClcdusualtNavigation).WithMany(p => p.ClientesClcdusualtNavigation).HasConstraintName("FK_UsuarioAlt_Cliente");

            entity.HasOne(d => d.ClcdusucadNavigation).WithMany(p => p.ClientesClcdusucadNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioCad_Cliente");

            entity.HasOne(d => d.ClnacionalidadeNavigation).WithMany(p => p.Clientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Nacionalidades_Cliente");
        });

        modelBuilder.Entity<Concessao>(entity =>
        {
            entity.HasOne(d => d.CccdfunNavigation).WithMany()
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Funcionalidades_Concessao");

            entity.HasOne(d => d.CccdusuNavigation).WithMany()
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Concessao");
        });

        modelBuilder.Entity<Enderecos>(entity =>
        {
            entity.HasKey(e => e.Edid).HasName("PK__Endereco__27751757199C6288");

            entity.HasOne(d => d.EdcdusualtNavigation).WithMany(p => p.EnderecosEdcdusualtNavigation).HasConstraintName("FK_UsuarioAlt_Enderecos");

            entity.HasOne(d => d.EdcdusucadNavigation).WithMany(p => p.EnderecosEdcdusucadNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioCad_Enderecos");
        });

        modelBuilder.Entity<Funcionalidades>(entity =>
        {
            entity.HasKey(e => e.Fnid).HasName("PK__Funciona__923A103913BA7C6B");
        });

        modelBuilder.Entity<Nacionalidades>(entity =>
        {
            entity.HasKey(e => e.Ncid).HasName("PK__Nacional__D945EEF76703BECC");
        });

        modelBuilder.Entity<SituacaoCliente>(entity =>
        {
            entity.HasKey(e => e.Scid).HasName("PK__Situacao__F7FE93AC6887BDE8");
        });

        modelBuilder.Entity<TipoCliente>(entity =>
        {
            entity.HasKey(e => e.Tcid).HasName("PK__TipoClie__B773707F532C8371");
        });

        modelBuilder.Entity<TipoUsuario>(entity =>
        {
            entity.HasKey(e => e.Tuid).HasName("PK__TipoUsua__81338C4E22646EB2");

            entity.HasOne(d => d.TuusualtNavigation).WithMany(p => p.TipoUsuarioTuusualtNavigation).HasConstraintName("FK_UsuarioAlt_TipoUsuario");

            entity.HasOne(d => d.TuusucadNavigation).WithMany(p => p.TipoUsuarioTuusucadNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioCad_TipoUsuario");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Usid).HasName("PK__Usuario__AA6401D519F5CD7A");

            entity.Property(e => e.Usaltsenha).IsFixedLength();

            entity.HasOne(d => d.UscdtpusuNavigation).WithMany(p => p.Usuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TipoUsuario_Usuario");

            entity.HasOne(d => d.UsusualtNavigation).WithMany(p => p.InverseUsusualtNavigation).HasConstraintName("FK_UsuarioAlt_Usuario");

            entity.HasOne(d => d.UsusucadNavigation).WithMany(p => p.InverseUsusucadNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioCad_Usuario");

            entity.HasOne(d => d.UsusurespNavigation).WithMany(p => p.InverseUsusurespNavigation).HasConstraintName("FK_UsuarioResp_Usuario");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}