// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class Enderecos
{
    [Key]
    [Column("EDID")]
    public int Edid { get; set; }

    [Required]
    [Column("EDLOGRADOURO")]
    [StringLength(255)]
    [Unicode(false)]
    public string Edlogradouro { get; set; }

    [Column("EDNUMERO")]
    [StringLength(6)]
    [Unicode(false)]
    public string Ednumero { get; set; }

    [Required]
    [Column("EDBAIRRO")]
    [StringLength(30)]
    [Unicode(false)]
    public string Edbairro { get; set; }

    [Required]
    [Column("EDCIDADE")]
    [StringLength(30)]
    [Unicode(false)]
    public string Edcidade { get; set; }

    [Required]
    [Column("EDUF")]
    [StringLength(2)]
    [Unicode(false)]
    public string Eduf { get; set; }

    [Column("EDCOMPL")]
    [StringLength(20)]
    [Unicode(false)]
    public string Edcompl { get; set; }

    [Required]
    [Column("EDCEP")]
    [StringLength(8)]
    [Unicode(false)]
    public string Edcep { get; set; }

    [Column("EDTPEND")]
    public int Edtpend { get; set; }

    [Column("EDEXCLUIDO")]
    public bool Edexcluido { get; set; }

    [Column("EDDTCAD", TypeName = "smalldatetime")]
    public DateTime Eddtcad { get; set; }

    [Column("EDCDUSUCAD")]
    public int Edcdusucad { get; set; }

    [Column("EDDTALT", TypeName = "smalldatetime")]
    public DateTime? Eddtalt { get; set; }

    [Column("EDCDUSUALT")]
    public int? Edcdusualt { get; set; }

    [InverseProperty("ClcdenderecoNavigation")]
    public virtual ICollection<Clientes> Clientes { get; } = new List<Clientes>();

    [ForeignKey("Edcdusualt")]
    [InverseProperty("EnderecosEdcdusualtNavigation")]
    public virtual Usuario EdcdusualtNavigation { get; set; }

    [ForeignKey("Edcdusucad")]
    [InverseProperty("EnderecosEdcdusucadNavigation")]
    public virtual Usuario EdcdusucadNavigation { get; set; }
}