// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class Funcionalidades
{
    [Key]
    [Column("FNID")]
    public int Fnid { get; set; }

    [Required]
    [Column("FNNOME")]
    [StringLength(255)]
    [Unicode(false)]
    public string Fnnome { get; set; }

    [Required]
    [Column("FNDESCRICAO")]
    [StringLength(255)]
    [Unicode(false)]
    public string Fndescricao { get; set; }

    [Column("FNEXCLUIDO")]
    public bool Fnexcluido { get; set; }
}