// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class Nacionalidades
{
    [Key]
    [Column("NCID")]
    public int Ncid { get; set; }

    [Required]
    [Column("NCSigla")]
    [StringLength(2)]
    [Unicode(false)]
    public string Ncsigla { get; set; }

    [Required]
    [Column("NCNome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Ncnome { get; set; }

    [InverseProperty("ClnacionalidadeNavigation")]
    public virtual ICollection<Clientes> Clientes { get; } = new List<Clientes>();
}