// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class SituacaoCliente
{
    [Key]
    [Column("SCID")]
    public int Scid { get; set; }

    [Required]
    [Column("SCNOME")]
    [StringLength(100)]
    [Unicode(false)]
    public string Scnome { get; set; }

    [Required]
    [Column("SCDESCRICAO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Scdescricao { get; set; }

    [Column("SCEXCLUIDO")]
    public bool Scexcluido { get; set; }

    [InverseProperty("ClcdsituacaoNavigation")]
    public virtual ICollection<Clientes> Clientes { get; } = new List<Clientes>();
}