// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class TipoCliente
{
    [Key]
    [Column("TCID")]
    public int Tcid { get; set; }

    [Required]
    [Column("TCNome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Tcnome { get; set; }

    [Required]
    [Column("TCDescricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Tcdescricao { get; set; }

    [Column("TCEXCLUIDO")]
    public bool Tcexcluido { get; set; }

    [InverseProperty("ClcdtipoclienteNavigation")]
    public virtual ICollection<Clientes> Clientes { get; } = new List<Clientes>();
}