// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

public partial class TipoUsuario
{
    [Key]
    [Column("TUID")]
    public int Tuid { get; set; }

    [Required]
    [Column("TUNOME")]
    [StringLength(25)]
    [Unicode(false)]
    public string Tunome { get; set; }

    [Column("TUDESCRICAO")]
    [StringLength(255)]
    [Unicode(false)]
    public string Tudescricao { get; set; }

    [Column("TUDTCAD", TypeName = "smalldatetime")]
    public DateTime Tudtcad { get; set; }

    [Column("TUUSUCAD")]
    public int Tuusucad { get; set; }

    [Column("TUDTALT", TypeName = "smalldatetime")]
    public DateTime? Tudtalt { get; set; }

    [Column("TUUSUALT")]
    public int? Tuusualt { get; set; }

    [ForeignKey("Tuusualt")]
    [InverseProperty("TipoUsuarioTuusualtNavigation")]
    public virtual Usuario TuusualtNavigation { get; set; }

    [ForeignKey("Tuusucad")]
    [InverseProperty("TipoUsuarioTuusucadNavigation")]
    public virtual Usuario TuusucadNavigation { get; set; }

    [InverseProperty("UscdtpusuNavigation")]
    public virtual ICollection<Usuario> Usuario { get; } = new List<Usuario>();
}