// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Index("Usnomeusu", Name = "UC_USNOMEUSU", IsUnique = true)]
public partial class Usuario
{
    [Key]
    [Column("USID")]
    public int Usid { get; set; }

    [Required]
    [Column("USNOMEUSU")]
    [StringLength(25)]
    [Unicode(false)]
    public string Usnomeusu { get; set; }

    [Required]
    [Column("USSENHA")]
    [StringLength(255)]
    [Unicode(false)]
    public string Ussenha { get; set; }

    [Column("USALTSENHA")]
    [StringLength(1)]
    [Unicode(false)]
    public string Usaltsenha { get; set; }

    [Column("USCDTPUSU")]
    public int Uscdtpusu { get; set; }

    [Column("USNUMACES")]
    public int Usnumaces { get; set; }

    [Column("USEXCLUIDO")]
    public bool Usexcluido { get; set; }

    [Column("USOBS")]
    [StringLength(255)]
    [Unicode(false)]
    public string Usobs { get; set; }

    [Column("USUSURESP")]
    public int? Ususuresp { get; set; }

    [Column("USDTCAD", TypeName = "smalldatetime")]
    public DateTime Usdtcad { get; set; }

    [Column("USUSUCAD")]
    public int Ususucad { get; set; }

    [Column("USDTALT", TypeName = "smalldatetime")]
    public DateTime? Usdtalt { get; set; }

    [Column("USUSUALT")]
    public int? Ususualt { get; set; }

    [InverseProperty("ClcdusualtNavigation")]
    public virtual ICollection<Clientes> ClientesClcdusualtNavigation { get; } = new List<Clientes>();

    [InverseProperty("ClcdusucadNavigation")]
    public virtual ICollection<Clientes> ClientesClcdusucadNavigation { get; } = new List<Clientes>();

    [InverseProperty("EdcdusualtNavigation")]
    public virtual ICollection<Enderecos> EnderecosEdcdusualtNavigation { get; } = new List<Enderecos>();

    [InverseProperty("EdcdusucadNavigation")]
    public virtual ICollection<Enderecos> EnderecosEdcdusucadNavigation { get; } = new List<Enderecos>();

    [InverseProperty("UsusualtNavigation")]
    public virtual ICollection<Usuario> InverseUsusualtNavigation { get; } = new List<Usuario>();

    [InverseProperty("UsusucadNavigation")]
    public virtual ICollection<Usuario> InverseUsusucadNavigation { get; } = new List<Usuario>();

    [InverseProperty("UsusurespNavigation")]
    public virtual ICollection<Usuario> InverseUsusurespNavigation { get; } = new List<Usuario>();

    [InverseProperty("TuusualtNavigation")]
    public virtual ICollection<TipoUsuario> TipoUsuarioTuusualtNavigation { get; } = new List<TipoUsuario>();

    [InverseProperty("TuusucadNavigation")]
    public virtual ICollection<TipoUsuario> TipoUsuarioTuusucadNavigation { get; } = new List<TipoUsuario>();

    [ForeignKey("Uscdtpusu")]
    [InverseProperty("Usuario")]
    public virtual TipoUsuario UscdtpusuNavigation { get; set; }

    [ForeignKey("Ususualt")]
    [InverseProperty("InverseUsusualtNavigation")]
    public virtual Usuario UsusualtNavigation { get; set; }

    [ForeignKey("Ususucad")]
    [InverseProperty("InverseUsusucadNavigation")]
    public virtual Usuario UsusucadNavigation { get; set; }

    [ForeignKey("Ususuresp")]
    [InverseProperty("InverseUsusurespNavigation")]
    public virtual Usuario UsusurespNavigation { get; set; }
}