USE master
GO

IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'CUSTOMSYS')
	DROP DATABASE CUSTOMSYS
GO 

IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = N'CUSTOMSYS')
	CREATE DATABASE CUSTOMSYS
GO

USE CUSTOMSYS
GO

IF OBJECT_ID('Usuario', 'U') IS NOT NULL
BEGIN
	DROP TABLE Usuario
END
GO

CREATE TABLE Usuario(
	USID		INT IDENTITY(1,1) PRIMARY KEY,
	USNOMEUSU	VARCHAR(25) NOT NULL,
	USSENHA		VARCHAR(255) NOT NULL,
	-- S- Deve Alterar senha no próximo login, N- Não necessário
	USALTSENHA	CHAR(1),
	-- S- Supervisor, U- Usuário, G- Gerente
	USCDTPUSU	INT NOT NULL,
	USNUMACES	INT DEFAULT(0) NOT NULL,
	USEXCLUIDO	BIT DEFAULT(0) NOT NULL,
	USOBS		VARCHAR(255),
	USUSURESP	INT,
	USDTCAD		SMALLDATETIME NOT NULL,
	USUSUCAD	INT NOT NULL,
	USDTALT		SMALLDATETIME,
	USUSUALT	INT,
	
CONSTRAINT  UC_USNOMEUSU UNIQUE (USNOMEUSU),

CONSTRAINT FK_UsuarioResp_Usuario
FOREIGN KEY (USUSURESP)
REFERENCES Usuario (USID),

CONSTRAINT FK_UsuarioAlt_Usuario
FOREIGN KEY (USUSUALT)
REFERENCES Usuario (USID)
)
GO

INSERT INTO Usuario (USNOMEUSU, USSENHA, USALTSENHA, USCDTPUSU, USNUMACES, USEXCLUIDO, USDTCAD, USUSUCAD) VALUES ('Master', 'E10ADC3949BA59ABBE56E057F20F883E', 'N', 1, 0, 0, GETDATE(), 1)
GO

ALTER TABLE Usuario
ADD CONSTRAINT FK_UsuarioCad_Usuario FOREIGN KEY (USUSUCAD) REFERENCES Usuario (USID);
GO

IF OBJECT_ID('TipoUsuario', 'U') IS NOT NULL
BEGIN
	DROP TABLE TipoUsuario
END
GO

CREATE TABLE TipoUsuario(
	TUID		INT IDENTITY(1,1) PRIMARY KEY,
	TUNOME		VARCHAR(25) NOT NULL,
	TUDESCRICAO	VARCHAR(255),
	TUDTCAD		SMALLDATETIME NOT NULL,
	TUUSUCAD	INT NOT NULL,
	TUDTALT		SMALLDATETIME,
	TUUSUALT	INT,
	
CONSTRAINT FK_UsuarioCad_TipoUsuario
FOREIGN KEY (TUUSUCAD)
REFERENCES Usuario (USID),

CONSTRAINT FK_UsuarioAlt_TipoUsuario
FOREIGN KEY (TUUSUALT)
REFERENCES Usuario (USID),
)
GO

INSERT INTO TipoUsuario (TUNOME, TUDESCRICAO, TUDTCAD, TUUSUCAD) VALUES ('Master', 'Usuário Master', GETDATE(), 1)

ALTER TABLE Usuario
ADD CONSTRAINT FK_TipoUsuario_Usuario FOREIGN KEY (USCDTPUSU) REFERENCES TipoUsuario(TUID);
GO

IF OBJECT_ID('Funcionalidades', 'U') IS NOT NULL
BEGIN
	DROP TABLE Funcionalidades
END
GO

CREATE TABLE Funcionalidades(
	FNID		INT IDENTITY(1,1) PRIMARY KEY,
	FNNOME		VARCHAR(255) NOT NULL,
	FNDESCRICAO	VARCHAR(255) NOT NULL,
	FNEXCLUIDO	BIT DEFAULT(0) NOT NULL
)
GO

IF OBJECT_ID('Concessao', 'U') IS NOT NULL
BEGIN
	DROP TABLE Concessao
END
GO

CREATE TABLE Concessao(
	CCCDFUN		INT NOT NULL,
	CCCDUSU		INT NOT NULL,

CONSTRAINT FK_Funcionalidades_Concessao
FOREIGN KEY (CCCDFUN)
REFERENCES Funcionalidades (FNID),

CONSTRAINT FK_Usuario_Concessao
FOREIGN KEY (CCCDUSU)
REFERENCES Usuario (USID),
)
GO


IF OBJECT_ID('Enderecos', 'U') IS NOT NULL
BEGIN
	DROP TABLE Enderecos
END
GO

CREATE TABLE Enderecos (
	EDID			INT IDENTITY(1,1) PRIMARY KEY,
	EDLOGRADOURO	Varchar(255) NOT NULL,
	EDNUMERO		VARCHAR(6),
	EDBAIRRO		VARCHAR(30) NOT NULL,
	EDCIDADE		VARCHAR(30) NOT NULL,
	EDUF			VARCHAR(2) NOT NULL,
	EDCOMPL			VARCHAR(20),
	EDCEP			VARCHAR(8)  NOT NULL,
	--Tipo do endereço: 0- Residencial, 1- Comercial 
	EDTPEND			INT NOT NULL,
	EDEXCLUIDO		BIT DEFAULT(0) NOT NULL,
	EDDTCAD			SMALLDATETIME NOT NULL,
	EDCDUSUCAD		INT	NOT NULL,
	EDDTALT			SMALLDATETIME,
	EDCDUSUALT		INT,

CONSTRAINT FK_UsuarioCad_Enderecos
FOREIGN KEY (EDCDUSUCAD)
REFERENCES Usuario (USID),

CONSTRAINT FK_UsuarioAlt_Enderecos
FOREIGN KEY (EDCDUSUALT)
REFERENCES Usuario (USID),
)
GO


IF OBJECT_ID('Nacionalidades', 'U') IS NOT NULL
BEGIN
	DROP TABLE Nacionalidades
END
GO

CREATE TABLE Nacionalidades (
    NCID INT IDENTITY PRIMARY KEY,
    NCSigla VARCHAR(2) NOT NULL,
    NCNome VARCHAR(100) NOT NULL
);
GO

IF OBJECT_ID('TipoCliente', 'U') IS NOT NULL
BEGIN
	DROP TABLE TipoCliente
END
GO

CREATE TABLE TipoCliente (
    TCID		INT IDENTITY PRIMARY KEY,
    TCNome		VARCHAR(100) NOT NULL,
    TCDescricao	VARCHAR(100) NOT NULL,
	TCEXCLUIDO	BIT DEFAULT(0) NOT NULL
);
GO

IF OBJECT_ID('SituacaoCliente', 'U') IS NOT NULL
BEGIN
	DROP TABLE SituacaoCliente
END
GO

CREATE TABLE SituacaoCliente (
    SCID		INT IDENTITY PRIMARY KEY,
    SCNOME		VARCHAR(100) NOT NULL,
    SCDESCRICAO	VARCHAR(100) NOT NULL,
	SCEXCLUIDO	BIT DEFAULT(0) NOT NULL
);
GO

IF OBJECT_ID('Clientes', 'U') IS NOT NULL
BEGIN
	DROP TABLE Clientes
END
GO

CREATE TABLE Clientes(
	CLID			VARCHAR(15) Primary Key ,
	CLNOME			VARCHAR(255) NOT NULL,
	CLCGC			VARCHAR(18) NOT NULL,
	CLSEXO			CHAR(1) NOT NULL,
	CLCDENDERECO	INT NOT NULL,
	CLEMAIL			VARCHAR(255),
	CLTELEFONE		VARCHAR(13),
	CLOBS			VARCHAR(255),
	-- 1- Ativo, 0- Inativo
	CLEXCLUIDO		BIT DEFAULT(0) NOT NULL,
	CLCDTIPOCLIENTE	INT NOT NULL,
	CLCDSITUACAO	INT NOT NULL,
	CLNACIONALIDADE INT NOT NULL,
	CLDTNASC		SMALLDATETIME NOT NULL,
	CLDTCAD			SMALLDATETIME NOT NULL,
	CLCDUSUCAD		INT NOT NULL,
	CLDTALT			SMALLDATETIME,
	CLCDUSUALT		INT,

CONSTRAINT FK_Enderecos_Cliente
FOREIGN KEY (CLCDENDERECO)
REFERENCES Enderecos (EDID),

CONSTRAINT FK_UsuarioCad_Cliente
FOREIGN KEY (CLCDUSUCAD)
REFERENCES Usuario (USID),

CONSTRAINT FK_UsuarioAlt_Cliente
FOREIGN KEY (CLCDUSUALT)
REFERENCES Usuario (USID),

CONSTRAINT FK_TipoCliente_Cliente
FOREIGN KEY (CLCDTIPOCLIENTE)
REFERENCES TipoCliente (TCID),

CONSTRAINT FK_SituacaoCliente_Cliente
FOREIGN KEY (CLCDSITUACAO)
REFERENCES SituacaoCliente (SCID),

CONSTRAINT FK_Nacionalidades_Cliente
FOREIGN KEY (CLNACIONALIDADE)
REFERENCES Nacionalidades (NCID),

CONSTRAINT  UC_CLCGC UNIQUE (CLCGC)
)
GO

